"""
Player tracking analytics and visualisations.

Uses the NGS (Next Gen Stats) sample for player 43540.
Produces:
  - Field heat map of player positions
  - Speed profile over a play
  - Per-event movement summary

On AWS these plots would be generated by a Glue/Lambda job and pushed to S3,
then surfaced through a QuickSight dashboard or via the API Gateway.
"""

from pathlib import Path

import matplotlib.pyplot as plt
import matplotlib.patches as patches
import numpy as np
import pandas as pd

from src.ingestion.data_loader import load_player_tracking

OUTPUT_DIR = Path(__file__).resolve().parents[2] / "outputs"

# NFL field dimensions in yards (coordinate system from Appendix 3A)
FIELD_LENGTH = 120  # including both end zones
FIELD_WIDTH = 53.3


def movement_summary(tracking: pd.DataFrame) -> pd.DataFrame:
    """Aggregate per-play movement stats."""
    return (
        tracking.groupby("PlayKey")
        .agg(
            total_distance=("dis", "sum"),
            max_speed=("s", "max"),
            avg_speed=("s", "mean"),
            duration_sec=("time", lambda x: x.max() - x.min()),
            n_events=("event", lambda x: (x != "").sum()),
        )
        .round(3)
        .reset_index()
    )


def plot_field_heatmap(tracking: pd.DataFrame, play_key: str | None = None, save: bool = True) -> None:
    """Density heat map of player positions across all (or one) play(s)."""
    data = tracking if play_key is None else tracking[tracking["PlayKey"] == play_key]

    fig, ax = plt.subplots(figsize=(14, 7))
    _draw_field(ax)

    h = ax.hexbin(
        data["x"], data["y"],
        gridsize=40,
        cmap="YlOrRd",
        mincnt=1,
        extent=[0, FIELD_LENGTH, 0, FIELD_WIDTH],
        alpha=0.8,
    )
    fig.colorbar(h, ax=ax, label="Frame count")

    title = f"Position Heat Map — Player 43540"
    if play_key:
        title += f" (Play {play_key})"
    ax.set_title(title, fontsize=14, fontweight="bold")
    ax.set_xlabel("Field length (yards)")
    ax.set_ylabel("Field width (yards)")

    _maybe_save(fig, "heatmap_positions.png", save)


def plot_speed_profile(tracking: pd.DataFrame, play_key: str, save: bool = True) -> None:
    """Speed over time for a single play, annotated with key events."""
    play = tracking[tracking["PlayKey"] == play_key].copy()
    if play.empty:
        print(f"No data for PlayKey {play_key}")
        return

    play = play.sort_values("time")
    events = play[play["event"] != ""][["time", "event"]]

    fig, ax = plt.subplots(figsize=(12, 4))
    ax.plot(play["time"], play["s"], color="#003594", linewidth=1.5, label="Speed (yds/s)")
    ax.fill_between(play["time"], play["s"], alpha=0.15, color="#003594")

    for _, row in events.iterrows():
        ax.axvline(row["time"], color="#D50A0A", linestyle="--", alpha=0.7, linewidth=0.9)
        ax.text(
            row["time"], play["s"].max() * 1.02,
            row["event"].replace("_", " "),
            rotation=45, fontsize=7, color="#D50A0A", ha="left",
        )

    ax.set_title(f"Speed Profile — Play {play_key}", fontsize=13, fontweight="bold")
    ax.set_xlabel("Time (seconds)")
    ax.set_ylabel("Speed (yards/second)")
    ax.legend()
    ax.grid(axis="y", linestyle=":", alpha=0.5)

    _maybe_save(fig, f"speed_profile_{play_key.replace('-', '_')}.png", save)


def plot_movement_path(tracking: pd.DataFrame, play_key: str, save: bool = True) -> None:
    """XY movement path for a single play with colour-coded speed."""
    play = tracking[tracking["PlayKey"] == play_key].copy().sort_values("time")
    if play.empty:
        print(f"No data for PlayKey {play_key}")
        return

    fig, ax = plt.subplots(figsize=(14, 7))
    _draw_field(ax)

    sc = ax.scatter(
        play["x"], play["y"],
        c=play["s"], cmap="coolwarm",
        s=12, zorder=5, alpha=0.85,
    )
    ax.plot(play["x"], play["y"], color="white", linewidth=0.6, alpha=0.5, zorder=4)
    fig.colorbar(sc, ax=ax, label="Speed (yds/s)")

    ax.set_title(f"Movement Path — Play {play_key}", fontsize=13, fontweight="bold")
    ax.set_xlabel("Field length (yards)")
    ax.set_ylabel("Field width (yards)")

    _maybe_save(fig, f"path_{play_key.replace('-', '_')}.png", save)


def _draw_field(ax: plt.Axes) -> None:
    """Draw a simplified NFL field background."""
    ax.set_facecolor("#3d7a3d")
    ax.set_xlim(0, FIELD_LENGTH)
    ax.set_ylim(0, FIELD_WIDTH)

    # End zones
    for x, color in [(0, "#1a4d1a"), (110, "#1a4d1a")]:
        ax.add_patch(patches.Rectangle((x, 0), 10, FIELD_WIDTH, color=color, zorder=1))

    # Yard lines every 10 yards
    for x in range(10, 111, 10):
        ax.axvline(x, color="white", linewidth=0.5, alpha=0.4, zorder=2)

    # Hash marks
    for x in range(10, 111, 1):
        for y in [22.9, 30.4]:
            ax.plot([x, x], [y - 0.3, y + 0.3], color="white", linewidth=0.4, alpha=0.5)

    ax.set_aspect("equal")


def _maybe_save(fig: plt.Figure, filename: str, save: bool) -> None:
    if save:
        OUTPUT_DIR.mkdir(exist_ok=True)
        path = OUTPUT_DIR / filename
        fig.tight_layout()
        fig.savefig(path, dpi=150, bbox_inches="tight")
        print(f"Saved: {path}")
        plt.close(fig)
    else:
        plt.tight_layout()
        plt.show()


if __name__ == "__main__":
    tracking = load_player_tracking()
    print(f"Tracking data: {len(tracking):,} frames across {tracking['PlayKey'].nunique()} plays")

    summary = movement_summary(tracking)
    print("\nMovement summary (top 5 plays by distance):")
    print(summary.nlargest(5, "total_distance").to_string(index=False))

    # Pick the play with the most frames for a clean visualisation
    busiest_play = tracking.groupby("PlayKey").size().idxmax()
    print(f"\nGenerating plots for play: {busiest_play}")

    plot_field_heatmap(tracking, save=True)
    plot_speed_profile(tracking, busiest_play, save=True)
    plot_movement_path(tracking, busiest_play, save=True)

    print("\nAll outputs written to outputs/")
